### ISSUE TITLE
How to reconstruct from sift?

### ISSUE THREAD

**Issue by sunshineatnoon** [aravindhm/deep-goggle#1]
Thanks for sharing this fantastic work! I managed to run experiment_cnn.m file, but I don't know how to run the sift experiment. I use this code to use a sift model:

image_for_sift = {'data/imagenet12-val/ILSVRC2012_val_00000043.JPEG'};
exp{end+1} = experiment_init('dsift',1,image_for_sift{1},ver,'cnn_sift',opts3);
experiment_run(exp) ;

It gives me this error:

Reference to non-existent field 'normalization'.
Error in compute_features (line 13)
normalize = get_cnn_normalize(net.normalization);

can you give me some hints?

**Comment by aravindhm** [comment]
We will update the experiments before CVPR (6th June). I'll have an experiment_dsift.m like script to make it run out of the box. Sorry for the delay.

**Comment by sunshineatnoon** [comment]
Thanks!

**Comment by aravindhm** [comment]
I have fixed the bug. experiment_shallow should cover dsift inversion.

**Comment by sunshineatnoon** [comment]
I tried, it works, thank you very much! :)
