### ISSUE TITLE
running my own vgg19 network

### ISSUE THREAD

**Issue by NerminSalem** [aravindhm/deep-goggle#10]
i m trying 
 net = load('imagenet-vgg-verydeep-19.mat') ;
>> im = imread('peppers.png') ;
>> im_ = single(im) ;
>> im_ = imresize(im_, net.meta.normalization.imageSize(1:2)) ;
>> res = vl_simplenn(net, im_) ;
>> y0=res(end-1).x;
>> res = invert_nn(net, y0, 'imgSize',net.meta.normalization.imageSize(1:2),'normalize',get_cnn_normalize(net.meta.normalization),'denormalize',get_cnn_denormalize(net.meta.normalization),'numRepeats',1);
Error: File: invert_nn.m Line: 46 Column: 6
The input character is not valid in MATLAB statements or expressions.
can u help me with that error?

**Comment by NerminSalem** [comment]
@aravindhm can u help?

**Comment by NerminSalem** [comment]
i tried res_inverse = invert_nn(net, y0, 'imgSize',net.meta.normalization.imageSize,'normalize',get_cnn_normalize(net.meta.normalization),'denormalize',get_cnn_denormalize(net.meta.normalization));
Error using  - 
Array dimensions must match for binary array op.

Error in invert_nn>nndistance (line 255)
  d = x - w ;

Error in invert_nn>nndistance_forward (line 244)
res_.x = nndistance(res.x, ly.w, ly.mask) ;

Error in vl_simplenn (line 374)
      res(i+1) = l.forward(l, res(i), res(i+1)) ;

Error in invert_nn (line 116)
res = vl_simplenn(net, x); % x is the random initialized image
but still the same error

**Comment by aravindhm** [comment]
I think that `y0` is the wrong size. How did you set `y0`?

**Comment by NerminSalem** [comment]
first thanks alot for your reply 
i set y0=res(end-1).x;

**Comment by aravindhm** [comment]
Unless `res(end-1).x` and `res(end).x` are the same size this will result in a size mismatch error. The network adds a l2 loss comparison at the end of `net` and uses `y0` as the reference for this comparison.

**Comment by NerminSalem** [comment]
i will check the size of the 2 layers but if there are not of the same size, what do u recommend ?

**Comment by aravindhm** [comment]
If they are not the same size then truncate the network `net.layers = net.layers(1:end-1)` before passing it to `invert_nn`. Please let me know if this works.

**Comment by NerminSalem** [comment]
thanks alot i will try it and send u my feedback

**Comment by NerminSalem** [comment]
i m sorry where to define net.layers = net.layers(1:end-1)?

**Comment by NerminSalem** [comment]
>> res = vl_simplenn(net, im_) ;
>> y0=res(end-1).x;
>> net.layers = net.layers(1:end-1)

net = 

    layers: {1x41 cell}
      meta: [1x1 struct]
>> res = invert_nn(net, y0, 'imgSize',net.meta.normalization.imageSize(1:2),'normalize',get_cnn_normalize(net.meta.normalization),'denormalize',get_cnn_denormalize(net.meta.normalization),'numRepeats',1);

i m getting the following errors:
Error using vl_nnconv
The FILTERS depth does not divide the DATA depth.

Error in vl_simplenn (line 300)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...

Error in invert_nn (line 116)
res = vl_simplenn(net, x); % x is the random initialized image

**Comment by aravindhm** [comment]
Something seems to have gone wrong with `numRepeats == 1`. I will need to investigate this. I will have time tomorrow.

**Comment by NerminSalem** [comment]
thanks alot for yr help, i really appreciate it
waiting for yr reply

**Comment by NerminSalem** [comment]
@aravindhm did u had a chance to look for the error?
thanks

**Comment by aravindhm** [comment]
I thing the commit should fix it. Use it as 

res_inverse = invert_nn(net, y0, ...
                        'imgSize', net.meta.normalization.imageSize, ...
                        'normalize', get_cnn_normalize(net.meta.normalization), ...
                        'denormalize', get_cnn_denormalize(net.meta.normalization));

**Comment by NerminSalem** [comment]
yes it worked, thank you so much, i really appreciate it
thankssssssssssssssssssssss
