### ISSUE TITLE
how to extract features from layer 43 (RELU)-vgg19

### ISSUE THREAD

**Issue by NerminSalem** [aravindhm/deep-goggle#11]
sorry for asking again but i want to extract features of layer 43 of vgg19 model (RELU)
and whenever i try y0=res(end-3).x;
it result in an error
Error using  - 
Array dimensions must match for binary array op.

Error in invert_nn>nndistance (line 255)
  d = x - w ;

Error in invert_nn>nndistance_forward (line 244)
res_.x = nndistance(res.x, ly.w, ly.mask) ;

Error in vl_simplenn (line 374)
      res(i+1) = l.forward(l, res(i), res(i+1)) ;
although  y0=res(end-2).x; have the same dimension as (end-3)
can u help?

**Comment by NerminSalem** [comment]
also another question when i extracted features of end layer using vgg19 it took more than 6 hours to reach a convergence, while when using alexnet end layer it gave more accurate results in almost 20 mins?
vgg19 suppose to give error rate less than that of alexnet, shouldn't that mean a better features representation?
sorry if i had soo many questions but yr work is really interesting
![alexnet_end](https://cloud.githubusercontent.com/assets/26221951/25317441/f7d024e8-2878-11e7-8cc0-e8ac3f571511.png)
![vgg19_end](https://cloud.githubusercontent.com/assets/26221951/25317445/085c8554-2879-11e7-95ab-ee06a5d24601.png)
![grannyapple](https://cloud.githubusercontent.com/assets/26221951/25317446/0dd719ae-2879-11e7-984f-9dffc9c55276.png)

**Comment by aravindhm** [comment]
Did you truncate the network in the same way 
`net.layers = net.layers(1:end-3)` ?

As for VGG-19 being very slow, it is because of the network is massive and each forward pass takes much longer than for alexnet. Also, the hyperparameters were tuned for Alexnet. If you want to play with VGG-19 it might be better to use the code here - https://github.com/aravindhm/nnpreimage.

**Comment by NerminSalem** [comment]
where to truncate the network
net.layers = net.layers(1:end-3)? in matlab prompt or within the code?

**Comment by NerminSalem** [comment]
yes it worked, thanks alot for your help and support
will check the link you provide, i understand the process much better now
