### ISSUE TITLE
Wrong Net object 

### ISSUE THREAD

**Issue by ghost** [aravindhm/deep-goggle#12]
I run the experiment_cnn as the README.MD does.
However, I got the following error message:

```
Reference to non-existent field 'meta'.
Error in experiment_run>run_one (line 41)
    exp.opts.normalize = get_cnn_normalize(net.meta.normalization) ;
```

I got the CNN-A net from the link you provide: http://www.robots.ox.ac.uk/~aravindh/networks.html
the CNN-A net `imagenet-caffe-ref.mat` does not have a field `meta`

However, it does have net.normalization.

I thought it is because the net in your link is too old?

Should I download a newer `imagenet-caffe-ref.mat` in MatConvNet homepage?

thanks a lot @aravindhm

**Comment by ghost** [comment]
I've found it's becasue the matconvenet version change
add the following line 
`net = vl_simplenn_tidy(net) ;` 
after the line 40 `net = load('networks/imagenet-caffe-ref.mat') ;` in the experiment_run.m
can solve the problem

or let user download from this website to get the newer version of the network can also solve it.
[MatConvNet trained networks](http://www.vlfeat.org/matconvnet/models/imagenet-caffe-ref.mat
)

**Comment by aravindhm** [comment]
@hhxjzyr  Thanks for reporting this issue and the possible fix. Sorry for the late response. I will make a commit with `net = vl_simplenn_tidy(net) ;` to make it more version agnostic.

**Comment by aravindhm** [comment]
@hhxjzyr I have made the change. If time permits, please give it a try and let me know if it works for you.

**Comment by ghost** [comment]
@aravindhm  Thanks, it works for me
