### ISSUE TITLE
in invert_nn.m about backpropagation

### ISSUE THREAD

**Issue by GlowingHorse** [aravindhm/deep-goggle#14]
if opts.lambdaL2 > 0 % Cost and derivative of L\beta norm
     r_ = sum(x(:).^opts.beta) ;
     dr_ = opts.beta * x.^(opts.beta-1) ;
     E(3,t) = opts.lambdaL2/2 * r_ ;
     dr = dr + opts.lambdaL2/2 * dr_ ;

In there, opts.lanbdaL2 seems like a empirical parameter. I would like to ask for advice about how to calculate the proper value of opts.lanbdaL2. Thank you very much.

**Comment by aravindhm** [comment]
@ShiRuiCV We intend to use the opts.beta'th power of the L-p norm. This has the desired soft box shape when we set opts.beta = 6. The parameter opts.lambdaL2 is tricky to set. If you aren't able to get it working in a few manual attempts, I suggest that you can our newer code https://github.com/aravindhm/nnpreimage which provides better normalization for all parts of the loss. We also set the opts.lambdaL2 automatically.

**Comment by GlowingHorse** [comment]
Thanks for your help, and I would like reading and try to reproduce the code.

The other question.
This is code from nnpreimage/layers/tv.m about the backpropagation of TV.

```
 np = max(v, 1e-6).^(1 - 2/beta) ;
  d1_ = np .* d1;
  d2_ = np .* d2;
  d11 = d1_(:,[1 1:end-1],:,:) - d1_ ;
  d22 = d2_([1 1:end-1],:,:,:) - d2_ ;
  d11(:,1,:,:) = - d1_(:,1,:,:) ;
  d22(1,:,:,:) = - d2_(1,:,:,:) ;
  dx = (beta/numPixels) * (d11 + d22) ;
```
If it's convenient, could you please tell me the paper or computing method of d11 = d1_(:,[1 1:end-1],:,:) - d1_ ; ? I just cannot get the right back propagation function there. It seems like using Euler Lagrange equation to get this, not the common derivative.

**Comment by aravindhm** [comment]
@ShiRuiCV The code is computing the derivative only, nothing fancy. I don't have any references for it though. `d11 = d1_(:, [1 1:end-1], :, :) - d1_ ;` is coming from the derivative of `(x_2 - x_1)^2` part of the TV norm.

**Comment by GlowingHorse** [comment]
Thank you very much. I have understand it.
