### ISSUE TITLE
how to get x0_sigma.mat, if I use other dataset rather than ImageNet

### ISSUE THREAD

**Issue by zxwedu** [aravindhm/deep-goggle#15]
I want to try inverting Le-Net using mnist. So, I want to know how I can get x0_sigma.mat and what is the content of x0_sigma.mat. Thank you.

**Comment by zxwedu** [comment]
Sorry, Sir. I just find this 'σ is the average Euclidean norm of natural images in a training set' in the paper. I know how to get x0_sigma. Thank you.

**Comment by aravindhm** [comment]
Did it work for Le-Net using mnist?

**Comment by zxwedu** [comment]
> Did it work for Le-Net using mnist?

yes, It works for Le-Net.
