### ISSUE TITLE
filnames of images inverted in the paper

### ISSUE THREAD

**Issue by tumble-weed** [aravindhm/deep-goggle#2]
Hi,
could you provide the filenames of the images from imagenet validation (mokey, man holding fsh, texture etc etc.)  whose results were reported in the paper?

thanks

**Comment by aravindhm** [comment]
Figure 1 uses image ILSVRC2012_val_00000024.JPEG
Other figures are ILSVRC2012_val_00000043.JPEG (flamingo), ILSVRC2012_val_00000013.JPEG (monkey)
The latest commit has experiment files experiment_cnn.m and experiment_shallow.m which contain all the relevant filenames.

**Comment by tumble-weed** [comment]
thanks
