### ISSUE TITLE
how to run my own networks

### ISSUE THREAD

**Issue by iiwindii** [aravindhm/deep-goggle#4]
hi, I want to visualize my own networks, the following code is used:

net=load('imagenet-caffe-alex');

im = imread('peppers.png') ;
im_ = single(im) ; 
im_ = imresize(im_, net.normalization.imageSize(1:2)) ;
im_ = im_ - net.normalization.averageImage ;

res = vl_simplenn(net, im_) ;

y0=res(end-1).x;

res_inverse = invert_nn(net, y0, 'imgSize',net.normalization.imageSize,'normalize',get_cnn_normalize(net.normalization),'denormalize',...
                                                                     get_cnn_denormalize(net.normalization),'numRepeats',1);

it can work well. However, if I want to visualize the other layers, such as y0=res(2).x, the following error information occurs:

Array dimensions must match for binary array op.

Error in invert_nn>nndistance (line 255)
  d = x - w ;

Error in invert_nn>nndistance_forward (line 244)
res_.x = nndistance(res.x, ly.w, ly.mask) ;

Error in vl_simplenn (line 250)
      res(i+1) = l.forward(l, res(i), res(i+1)) ;

Error in invert_nn (line 116)
res = vl_simplenn(net, x); % x is the random initialized image

I have checked the error, but fail to solve this problem. Thanks in advance！

**Comment by iiwindii** [comment]
@aravindhm could you give me some advice?thanks！

**Comment by aravindhm** [comment]
Hi fengyunxiaozi,
for res(2).x, did you also change your net as net.layers = net.layers(1:2); ?

**Comment by iiwindii** [comment]
@aravindhm  thanks, that's the problem. I have ignored this change. But res(2).x is the response of conv1, if we want to visualize this layer, should the net be changed as net.layers = net.layers(1) rather than net.layers = net.layers(1:2)??

I  have another problem. how to examine reconstructions obtained from subset
of neural responses in different CNN layers just like Figure 9 in your paper? I have set opts.filterGroup=1 or 2 (in the invert_nn function), but I cannot get the wanted results.

Thanks in advance!

**Comment by aravindhm** [comment]
Oops! It's net.layers(1)

If your network is using filter groups then setting opts.filterGroup = 1 or 2 should invert only the concerned filter groups. It it is not using any filter groups then nothing should change. Alternatively, set opts.neigh = 1/2/3/4/5 etc. to see the effect of the central 1x1/2x2/3x3/4x4/5x5 neurons. You can also change the mask in line 68 and 69 to get any further effects. Let me know if that works.

**Comment by iiwindii** [comment]
@aravindhm it works now, and I understand this process better now. many thanks!

**Comment by NerminSalem** [comment]
hi, i m trying the following 
net = load('imagenet-vgg-verydeep-19.mat') ;

        im = imread('peppers.png') ;
        im_ = single(im) ;
        im_ = imresize(im_, net.meta.normalization.imageSize(1:2)) ;
        res = vl_simplenn(net, im_) ;
        y0=res(end-1).x;
 res_inverse = invert_nn(net, y0, 'imgSize',net.meta.normalization.imageSize,'normalize',get_cnn_normalize(net.meta.normalization),'denormalize',get_cnn_denormalize(net.meta.normalization));
Error using -
Array dimensions must match for binary array op.

Error in invert_nn>nndistance (line 255)
d = x - w ;

Error in invert_nn>nndistance_forward (line 244)
res_.x = nndistance(res.x, ly.w, ly.mask) ;

Error in vl_simplenn (line 374)
res(i+1) = l.forward(l, res(i), res(i+1)) ;

Error in invert_nn (line 116)
res = vl_simplenn(net, x); % x is the random initialized image
can u help, u said it worked with u, i m getting the same error with    y0=res(end-1).x; i m working with matlab 2015, can u help me with this error? 
@fengyunxiaozi @aravindhm @anguyen8
