### ISSUE TITLE
Reference to non-existent field 'weights'.

### ISSUE THREAD

**Issue by hosnasattar** [aravindhm/deep-goggle#7]
hi,
I try to run the  experiment_cnn, but I get error immediately after 
Starting an expeirmentrunning experiment ILSVRC2012_val_00000013
do you have any idea why I get this error?
Reference to non-existent field 'weights'.
Error in vl_simplenn (line 288)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...
Error in compute_features (line 19)
res = vl_simplenn(net, x0);
Error in experiment_run>run_one (line 74)
feats = compute_features(net, im, exp.opts);
Error in experiment_run (line 11)
    run_one(exp{i}) ;
Error in experiment_cnn (line 157)
experiment_run(exp) ;

**Comment by aravindhm** [comment]
It is an issue with matconvnet's simplenn network format changing over time.
Can you try adding
net = vl_simplenn_tidy(net); in line 70 of experiment_run.m 
If that works, please send me a pull request.

**Comment by hosnasattar** [comment]
yes, it solved. Thanks.
