### ISSUE TITLE
can this tool visualize the learned weights/filters of CNN?

### ISSUE THREAD

**Issue by iiwindii** [aravindhm/deep-goggle#9]
hi, can deep-goggle be used to visualize the learned filters of each layer of a CNN architecture?  After 

the network is trained, I just want to see what the learned filters look like.... Thanks in advance!

**Comment by aravindhm** [comment]
Yes. You need to change the opts.objective to 'innerproduct' and set ref to be a one hot vector selecting the neuron in question (see core/nn_invert.m). You will need to change the regularizer weights after changing the loss function. We have code to do this which I shall in the coming weeks.

**Comment by iiwindii** [comment]
thanks, I will try it. also, hope for your helpful tool
